### PR TITLE
Engbergt

### PR DESCRIPTION
**Pull request by tarrenitup**
RegEx bug caught. Detailed on Google Doc. Not sure if Aburas wants us to fix it in code or leave the bug.. I sent an email to him.

### CODE REVIEW

**Comment by KobaKiju** [comment]
We don't need to correct the bugs, just find and report on them. 

I can't merge this until the conflicts are resolved.

**Comment by KobaKiju** [comment]
Also, why are you going through and commenting out a bunch of the pom?

**Comment by tarrenitup** [comment]
The commented out stuff is evosuite junk that is causing my tests not to run. I'll fix that conflict in a minute.

**Comment by KobaKiju** [comment]
Removing the binary class files (which probably shouldn't be on git anyways) and re-commiting with those gone should fix the more complex Merge. 

After that, I assume the naming convention for ThirdPartitionTest/PortTest is another conflict. That should be able to be remedied in the web editor.

**Comment by tarrenitup** [comment]
hmm... i definitely removed the class files before pushing: mvn clean. I do remember seeing a 'target' file when pulling early this morning. Is it possible that the conflict is that I've 'deleted' the class files that may have already been in the master?

**Comment by KobaKiju** [comment]
I'll just write a quick .gitignore file. Heading out at the moment, I'll write it after ordering a coffee.

**Comment by KobaKiju** [comment]
Alright, wrote the gitignore and opened #7 for it. Delete the class binary files from your local repo, re-commit and push those changes to your branch. It'll automatically be included in your PR. 

After that, we can resolve the UrlValidatorTest conflicts in-browser.

**Comment by KobaKiju** [comment]
Resolved Merge Conflicts. Merging.

**Pull request merged**
